### ISSUE TITLE
RVA_020: Should Ssccfg be updated to Smcdeleg

### ISSUE THREAD

**Issue by punitagrawal** [riscv-non-isa/riscv-server-platform#19]
The privileged specification includes a chapter named **_"Smcdeleg" Counter Delegation Extension, Version 1.0.0_** that includes the description of Smcdeleg and Ssccfg.

There does not seem to be a standalone text for **_Ssccfg_**, it always seems to be referred in hyphenated context with **_Smcdeleg_**.

For clarity / ease of finding the description, it would be helpful to update the RVA_020 reference to **Smcdeleg** or **Smcdeleg / Ssccfg** if the join reference is important. 

Apologies if my search skills didn't find the right reference or am missing some backstory regarding the reference to Ssccfg in the server platform specification.

**Comment by andreiw** [comment]
Thanks, Punit. Can you propose a pull request with your suggested change? @punitagrawal
